# Generated by Django 4.1.2 on 2022-12-01 00:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('bir_date', models.DateField()),
                ('id_patient', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gov_id', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=30, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('W', 'W'), ('NON_BINARY', 'NON_BINARY')], max_length=30, null=True)),
                ('caregiver_id', models.CharField(max_length=30)),
                ('parole', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('bir_date', models.DateField()),
                ('id_doctor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gov_id', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('specialization', models.CharField(choices=[('Nurse', 'Nurse'), ('Doctor', 'Doctor')], max_length=12, null=True)),
                ('experience', models.CharField(max_length=12)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=12, null=True)),
                ('price', models.CharField(max_length=20)),
                ('schedule', models.CharField(max_length=50, null=True)),
                ('rating', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sent_date', models.DateField(auto_now_add=True, null=True)),
                ('accepted', models.BooleanField(default=False)),
                ('accepted_date', models.DateField(null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.department')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.doctor')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
