# Generated by Django 3.2.16 on 2022-11-02 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('bir_date', models.CharField(max_length=12)),
                ('id_doctor', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gov_id', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=11)),
                ('department', models.CharField(choices=[('medicine', 'medicine'), ('surgery', 'surgery'), ('gynecology', 'gynecology'), ('obstetrics', 'obstetrics'), ('pediatrics', 'pediatrics'), ('radiology', 'radiology'), ('eye', 'eye'), ('ENT', 'ENT'), ('dental', 'dental'), ('orthopedics', 'orthopedics'), ('neurology', 'neurology'), ('cardiology', 'cardiology'), ('psychiatry', 'psychiatry'), ('skin', 'skin')], max_length=12, null=True)),
                ('specialization', models.CharField(choices=[('nurse', 'nurse'), ('doctor', 'doctor')], max_length=12, null=True)),
                ('experience', models.CharField(max_length=12)),
                ('photo', models.ImageField(upload_to='uploads/')),
                ('category', models.CharField(choices=[('first', 'first'), ('second', 'second'), ('third', 'third')], max_length=12, null=True)),
                ('price', models.CharField(max_length=20)),
                ('schedule', models.CharField(max_length=50, null=True)),
                ('rating', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('bir_date', models.CharField(max_length=12)),
                ('id_patient', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gov_id', models.CharField(max_length=12)),
                ('first_name', models.CharField(max_length=30)),
                ('middle_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('blood_group', models.CharField(choices=[('O', 'O'), ('A', 'A'), ('B', 'B'), ('AB', 'AB')], max_length=30, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=11)),
                ('marital_status', models.CharField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced'), ('Widowed', 'Widowed'), ('Separated', 'Separated')], max_length=30, null=True)),
                ('gender', models.CharField(choices=[('M', 'M'), ('W', 'W'), ('NON_BINARY', 'NON_BINARY')], max_length=30, null=True)),
                ('caregiver_id', models.CharField(max_length=30)),
                ('parole', models.CharField(max_length=30)),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
