# Generated by Django 4.1.2 on 2022-11-30 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('sent_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bir_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='category',
            field=models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.CharField(choices=[('Medicine', 'Medicine'), ('Surgery', 'Surgery'), ('Gynecology', 'Gynecology'), ('Obstetrics', 'Obstetrics'), ('Pediatrics', 'Pediatrics'), ('Radiology', 'Radiology'), ('Eye', 'Eye'), ('ENT', 'ENT'), ('Dental', 'Dental'), ('Orthopedics', 'Orthopedics'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Psychiatry', 'Psychiatry'), ('Skin', 'Skin')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(choices=[('Nurse', 'Nurse'), ('Doctor', 'Doctor')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='bir_date',
            field=models.DateField(),
        ),
    ]
