# Generated by Django 4.1.2 on 2022-11-30 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_appointment_alter_doctor_bir_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='accepted_date',
            field=models.DateField(null=True),
        ),
    ]
