# Generated by Django 3.2.16 on 2022-11-02 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_patient_marital_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='parole',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
