# Generated by Django 4.1.2 on 2022-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_appointment_accepted_appointment_accepted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='sent_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
