# Generated by Django 3.2.16 on 2022-11-02 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_patient_parole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='parole',
            field=models.CharField(max_length=30),
        ),
    ]
