# Generated by Django 3.2.16 on 2022-11-02 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_patient_parole'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reg_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
